const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync('api/analyze.js','utf8');
function setup(fetch){const context=vm.createContext({module:{exports:{}},process:{env:{GEMINI_API_KEY:'test-only-server-key'}},console:{warn(){},info(){}},AbortController,setTimeout,clearTimeout,fetch});vm.runInContext(source+'\nmodule.exports.testing={validatePayload,validateResult,calculateIndices,makePrompt,RESPONSE_SCHEMA};',context);return context.module.exports;}
const api=setup();const helpers=api.testing;
function fixture(schema=helpers.RESPONSE_SCHEMA){if(schema.type==='object')return Object.fromEntries(Object.entries(schema.properties).map(([k,s])=>[k,fixture(s)]));if(schema.type==='array')return Array.from({length:schema.minItems},()=>fixture(schema.items));if(schema.type==='integer')return 82;return schema.enum?.[0]||'Person A и Person B: тестовый текст, а не настоящий AI-анализ.';}
const answers=Array.from({length:15},(_,i)=>({question:'Тестовый вопрос',personA:'Развёрнутый ответ участника',personB:'Другой развёрнутый ответ',type:i>=12?'free':'choice'}));
const invoke=async(handler,method,body)=>{const result={status:200,headers:{}};const res={setHeader(k,v){result.headers[k]=v},set statusCode(v){result.status=v},end(v){result.body=JSON.parse(v)}};await handler({method,body},res);return result;};
test('API rejects incomplete and malformed input without contacting Gemini',async()=>{const h=setup(()=>{throw Error('Must not call')});assert.equal((await invoke(h,'GET')).status,405);assert.equal((await invoke(h,'POST',{answers:[]})).status,400);assert.equal((await invoke(h,'POST',{answers:[...answers.slice(0,14),null]})).status,400)});
test('API uses same model, server-only header and protected data prompt',async()=>{let request;const data=fixture();data.council.at(-1).speaker='PARA';const h=setup(async(url,options)=>{request={url,options};return {ok:true,json:async()=>({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(data)}]}}]})}});const result=await invoke(h,'POST',{answers});assert.equal(result.status,200);assert.match(request.url,/gemini-3.1-flash-lite:generateContent$/);assert.ok(!request.url.includes('key='));assert.equal(request.options.headers['x-goog-api-key'],'test-only-server-key');assert.equal(result.body.analysisVersion,6);assert.ok(!JSON.stringify(result.body).includes('test-only-server-key'));assert.equal(Object.keys(result.body.metricNarratives).length,12);assert.match(JSON.parse(request.options.body).systemInstruction.parts[0].text,/untrusted data/)});
test('provider error, truncated generation, malformed result all degrade safely',async()=>{for(const response of [{ok:false,status:429},{ok:true,json:async()=>({candidates:[{finishReason:'MAX_TOKENS'}]})},{ok:true,json:async()=>({candidates:[{finishReason:'STOP',content:{parts:[{text:'{}'}]}}]})}]){const result=await invoke(setup(async()=>response),'POST',{answers});assert.equal(result.status,503);assert.ok(!JSON.stringify(result).includes('test-only-server-key'));}});
test('risk responds to multiple critical contradictions and semantic text signal',()=>{const metrics=Object.fromEntries(Object.keys(fixture().metrics).map(k=>[k,90]));const base=helpers.calculateIndices(metrics,10);metrics.trust=40;const one=helpers.calculateIndices(metrics,10);metrics.honesty=40;metrics.communication=40;const many=helpers.calculateIndices(metrics,10);const severeText=helpers.calculateIndices(metrics,90);assert.ok(base.breakupRiskIndex<one.breakupRiskIndex);assert.ok(many.breakupRiskIndex>one.breakupRiskIndex+15);assert.ok(severeText.breakupRiskIndex>=many.breakupRiskIndex+15);assert.equal(helpers.calculateIndices(Object.fromEntries(Object.keys(metrics).map(k=>[k,81])),20).breakupRiskIndex,19)});
const elements=new Map();const get=selector=>{if(!elements.has(selector))elements.set(selector,{value:'',style:{},classList:{contains:()=>false},setAttribute(){},querySelectorAll(){return[]}});return elements.get(selector)};
const client=vm.createContext({document:{querySelector:get,addEventListener(){},querySelectorAll(){return[]}},location:{},Date,console});const html=fs.readFileSync('index.html','utf8');vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],client);
test('every AI marker is personalized once and untrusted markup is escaped',()=>{vm.runInContext('S.names=["Саша <img src=x>","Аня $&"];',client);assert.equal(vm.runInContext('personalize("Person A + Person B / person_a")',client),'Саша <img src=x> + Аня $& / Саша <img src=x>');const safe=vm.runInContext('safeAI("Person A <script>alert(1)</script>")',client);assert.ok(!safe.includes('<'));assert.match(safe,/&lt;script&gt;/)});
test('client sends no names or dates fields and redacts repeated entered names',()=>{vm.runInContext('S.names=["Саша","Аня"]; S.dates=["2001-01-01","2002-02-02"]; S.a=[Array(12).fill(1).concat(["Саша хочет общий дом","Аня не любит ложь","Хочу говорить честно"]),Array(12).fill(2).concat(["Аня хочет путешествовать","Саша боится игнора","Не хочу скрывать обиды"])];',client);const payload=JSON.parse(vm.runInContext('JSON.stringify(buildAIPayload())',client));assert.deepEqual(Object.keys(payload),['answers']);assert.ok(!JSON.stringify(payload).includes('Саша'));assert.ok(!JSON.stringify(payload).includes('2001-01-01'));assert.match(payload.answers[12].personA,/Person A/)});
test('fallback gives normal adjacent-choice scores and never scores free text by words',()=>{assert.equal(vm.runInContext('optionSim(1,2,"trust")',client),81);assert.equal(vm.runInContext('calc().c.risk',client),null);assert.equal(vm.runInContext('calc().qScores[12]',client),null);assert.ok(!html.includes('premium=1'));assert.ok(!html.includes('Расчёт выполняется локально самим PARA'))});
// Local-only visual fixture, generated from the exact response contract.
if(process.env.PARA_WRITE_FIXTURE)fs.writeFileSync('/tmp/para-fixture.json',JSON.stringify(fixture()));
