'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{randomUUID}=require('node:crypto'),{execFileSync}=require('node:child_process');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'para-test-'));
process.env.TURSO_DATABASE_URL='file:'+path.join(dir,'test.db');process.env.REPORT_ENCRYPTION_KEY='ab'.repeat(32);process.env.GEMINI_API_KEY='unit-gemini-not-a-real-key';process.env.ADMIN_SECRET='unit-admin-'+ 'x'.repeat(40);process.env.APP_URL='https://para.test';process.env.PAYMENT_PROVIDER='demo';
const db=require('../lib/db'),S=require('../lib/security'),R=require('../lib/reports'),P=require('../lib/payments'),usage=require('../lib/coach-usage');const {payload,invoke,mockProvider,cookie,fixture}=require('./helpers.cjs');const analyze=require('../api/analyze'),coach=require('../api/coach'),premium=require('../api/premium'),reportRoute=require('../api/report'),checkout=require('../api/checkout'),webhook=require('../api/webhook'),events=require('../api/events'),admin=require('../api/admin');
const owner=S.session({headers:{cookie}}),realProvider=P.provider;
before(async()=>require('../scripts/migrate')());after(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true});});
async function create(){mockProvider();await db.execute('DELETE FROM rate_limits');const r=await invoke(analyze,'POST',payload());assert.equal(r.status,200,r.raw);return r.body;}
function stripeConfig(){process.env.PAYMENT_PROVIDER='stripe';process.env.PAYMENT_SECRET_KEY='sk_test_unit';process.env.PAYMENT_WEBHOOK_SECRET='whsec_unit_secret';process.env.PAYMENT_PRICE_ID='price_unit';}
function eventFor(p,id=randomUUID()){return {id:'evt_'+id,type:'checkout.session.completed',livemode:false,data:{object:{id:p.provider_payment_id||'cs_unit_'+p.id,mode:'payment',client_reference_id:p.report_id,metadata:{report_id:p.report_id,payment_id:p.id},amount_total:p.amount,currency:p.currency,payment_status:'paid',payment_intent:'pi_'+p.id}}};}
function signed(event,override={}){const raw=JSON.stringify(event),sig=require('stripe').webhooks.generateTestHeaderString({payload:raw,secret:process.env.PAYMENT_WEBHOOK_SECRET,...override});return invoke(webhook,'POST',Buffer.from(raw),{'stripe-signature':sig});}
async function insertPayment(id){const pid=randomUUID();await db.execute('INSERT INTO payments(id,provider,provider_payment_id,status,amount,currency,price_id,report_id,created_at,expires_at) VALUES(?,?,?,?,?,?,?,?,?,?)',[pid,'stripe','cs_'+pid,'pending',199,'usd','price_unit',id,Date.now(),Date.now()+3600000]);return db.one('SELECT * FROM payments WHERE id=?',[pid]);}
test('real SQL migration is repeatable; state persists across a different Node process',async()=>{await require('../scripts/migrate')();await db.execute("INSERT INTO analytics_events(id,anonymous_session_id,event_name,created_at) VALUES('persist','owner','landing_view',?)",[Date.now()]);const out=execFileSync(process.execPath,['-e',"require('./lib/db').one(\"SELECT id FROM analytics_events WHERE id='persist'\").then(x=>{console.log(x.id);require('./lib/db').close()})"],{cwd:path.resolve(__dirname,'..'),env:process.env,encoding:'utf8'});assert.match(out,/persist/);});
test('three-pass streaming sends only free fields; encrypted DB holds paid content, no raw answers',async()=>{const requests=mockProvider(),p=payload();const r=await invoke(analyze,'POST',{...p,stream:true});assert.deepEqual(r.events.map(e=>e.event),['accepted','base','complete']);assert.equal(requests.length,3);assert.ok(!r.raw.includes('PAID_ONLY_CANARY'));const result=r.events.at(-1).data;assert.equal(result.analysisVersion,8);assert.equal(result.premium,undefined);assert.equal(result.metricNarratives,undefined);assert.equal(Object.keys(result.metricPreviews).length,12);assert.equal(result.cycle.steps.length,1);const stored=await R.owned(result.reportId,owner);assert.ok(!stored.content_cipher.includes('PAID_ONLY_CANARY'));assert.equal(S.open(stored.content_cipher).premium.mainTrigger,'PAID_ONLY_CANARY_7Z9');assert.equal(stored.raw_answers,undefined);for(const {url,options}of requests){assert.ok(!url.includes('key='));assert.equal(options.headers['x-goog-api-key'],process.env.GEMINI_API_KEY);}assert.ok(!r.raw.includes(process.env.GEMINI_API_KEY));});
test('duplicate analysis reuses persisted report; changed payload cannot overwrite it',async()=>{mockProvider();const p=payload(),first=await invoke(analyze,'POST',p);global.fetch=()=>{throw Error('Should not regenerate');};const second=await invoke(analyze,'POST',p);assert.equal(second.body.reportId,first.body.reportId);p.answers[0].personA=3;assert.equal((await invoke(analyze,'POST',p)).status,409);});
test('premium rejects strangers, forged client flags and unpaid reports',async()=>{const r=await create();assert.equal((await invoke(premium,'GET',undefined,{}, {id:r.reportId})).status,402);assert.equal((await invoke(premium,'GET',undefined,{cookie:'para_session='+Buffer.alloc(32,2).toString('base64url')},{id:r.reportId})).status,404);assert.equal((await invoke(premium,'GET',{premium_unlocked:true},{},{id:r.reportId})).status,402);assert.equal((await invoke(reportRoute,'GET',undefined,{},{id:'../other'})).status,404);});
test('one free Coach response persists; duplicate retry does not charge; client tampering ignored',async()=>{const r=await create(),request={reportId:r.reportId,requestId:randomUUID(),question:'Как договориться о паузе после нашей ссоры?',premiumUnlocked:true,report:{premium:{secret:'FORGED'}}};const calls=mockProvider();let out=await invoke(coach,'POST',request);assert.equal(out.status,200,out.raw);assert.equal(out.body.coachFreeRemaining,0);assert.ok(!calls[0].options.body.includes('PAID_ONLY_CANARY'));assert.ok(!calls[0].options.body.includes('FORGED'));const duplicate=await invoke(coach,'POST',request);assert.equal(duplicate.body.answer,out.body.answer);assert.equal(calls.length,1);assert.equal((await invoke(coach,'POST',{...request,requestId:randomUUID(),question:'Другой вопрос о нашей семье'})).status,402);assert.equal((await R.owned(r.reportId,owner)).coach_free_used,1);});
test('failed Coach generation releases reservation; crash lease is recoverable',async()=>{const r=await create(),p={reportId:r.reportId,requestId:randomUUID(),question:'Почему нам трудно начать этот разговор?'};global.fetch=async()=>({ok:false,status:503});assert.equal((await invoke(coach,'POST',p)).status,503);assert.equal((await R.owned(r.reportId,owner)).coach_free_used,0);mockProvider();assert.equal((await invoke(coach,'POST',p)).status,200);const r2=await create(),slot=await usage.reserve(r2.reportId,owner,randomUUID(),'Как нам говорить о деньгах?');assert.equal((await usage.reserve(r2.reportId,owner,randomUUID(),'Как нам говорить о деньгах?')).pending,true);await db.execute('UPDATE coach_usage SET lease_until=0 WHERE id=?',[slot.usageId]);const recovered=await usage.reserve(r2.reportId,owner,randomUUID(),'Как нам говорить о деньгах?');assert.notEqual(recovered.attempt,slot.attempt);await assert.rejects(usage.finish(slot,'stale'),/повторно/);await usage.finish(recovered,'recovered answer');});
test('signed webhook unlocks exactly once; invalid signature, stale timestamp, altered amount and wrong mode fail',async()=>{stripeConfig();const r=await create(),p=await insertPayment(r.reportId),event=eventFor(p);const bad=await invoke(webhook,'POST',Buffer.from(JSON.stringify(event)),{'stripe-signature':'fake'});assert.equal(bad.status,400);assert.equal((await signed(event,{timestamp:1})).status,400);const altered=structuredClone(event);altered.data.object.amount_total=1;assert.equal((await signed(altered)).status,400);const wrong=structuredClone(event);wrong.livemode=true;assert.equal((await signed(wrong)).status,400);assert.equal((await signed(event)).status,200);assert.equal((await signed(event)).body.duplicate,true);assert.equal((await invoke(premium,'GET',undefined,{},{id:r.reportId})).body.premium.mainTrigger,'PAID_ONLY_CANARY_7Z9');assert.equal((await db.one("SELECT COUNT(*) AS n FROM analytics_events WHERE event_name='purchase_completed' AND entity_id=?",[p.id])).n,1);});
test('pending payment does not unlock; refund before completion cannot re-grant access',async()=>{stripeConfig();const r=await create(),p=await insertPayment(r.reportId),event=eventFor(p);event.data.object.payment_status='unpaid';assert.equal((await signed(event)).status,200);assert.equal((await R.owned(r.reportId,owner)).premium_unlocked,0);const refund={id:'evt_'+randomUUID(),type:'charge.refunded',livemode:false,data:{object:{payment_intent:'pi_'+p.id}}};assert.equal((await signed(refund)).status,200);assert.equal((await signed(eventFor(p))).status,200);assert.equal((await R.owned(r.reportId,owner)).premium_unlocked,0);});
test('verified purchase gives exactly eight paid Coach messages, no client quota override',async()=>{stripeConfig();const r=await create(),p=await insertPayment(r.reportId);await signed(eventFor(p));mockProvider();for(let i=0;i<9;i++){const out=await invoke(coach,'POST',{reportId:r.reportId,requestId:randomUUID(),question:'Как нам обсуждать отношения, вопрос '+i,limit:999});assert.equal(out.status,200,out.raw);}assert.equal((await invoke(coach,'POST',{reportId:r.reportId,requestId:randomUUID(),question:'Попробуем задать десятый вопрос'})).status,402);const row=await R.owned(r.reportId,owner);assert.equal(row.coach_free_used,1);assert.equal(row.coach_paid_used,8);});
test('concurrent reservations cannot consume more than one free slot',async()=>{const r=await create();const results=await Promise.allSettled([usage.reserve(r.reportId,owner,randomUUID(),'Первый параллельный вопрос'),usage.reserve(r.reportId,owner,randomUUID(),'Второй параллельный вопрос')]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal((await db.one("SELECT COUNT(*) AS n FROM coach_usage WHERE report_id=? AND status='pending'",[r.reportId])).n,1);});
test('checkout is bound to a server price and reuses one session; return URL cannot unlock',async()=>{stripeConfig();const r=await create();let creates=0;P.provider=()=>({kind:'stripe',price:async()=>({}),retrieve:async()=>({status:'open'}),create:async p=>{creates++;return {id:'cs_'+p.id,url:'https://checkout.stripe.com/c/pay/test_'+p.id};}});try{const first=await invoke(checkout,'POST',{reportId:r.reportId,amount:1}),second=await invoke(checkout,'POST',{reportId:r.reportId});assert.equal(first.status,200,first.raw);assert.equal(first.body.url,second.body.url);assert.equal(creates,1);assert.equal((await R.owned(r.reportId,owner)).premium_unlocked,0);assert.equal((await db.one('SELECT amount FROM payments WHERE report_id=?',[r.reportId])).amount,199);}finally{P.provider=realProvider;}});
test('analytics accepts only low-sensitivity client events, deduplicates, admin uses secret',async()=>{assert.equal((await invoke(events,'POST',{event:'purchase_completed'})).status,400);for(let i=0;i<2;i++)await invoke(events,'POST',{event:'landing_view',metadata:{name:'SECRET_NAME'}});assert.equal((await db.one("SELECT COUNT(*) AS n FROM analytics_events WHERE anonymous_session_id=? AND event_name='landing_view'",[owner])).n,1);assert.ok(!(await db.one("SELECT metadata FROM analytics_events WHERE anonymous_session_id=? AND event_name='landing_view'",[owner])).metadata.includes('SECRET_NAME'));assert.equal((await invoke(admin,'GET')).status,401);const out=await invoke(admin,'GET',undefined,{authorization:'Bearer '+process.env.ADMIN_SECRET});assert.equal(out.status,200);assert.ok(out.body.totalSessions>=1);assert.ok(out.body.purchases>=1);});
test('missing DB permits only free analysis; demo payment never fabricates success',async()=>{process.env.PAYMENT_PROVIDER='demo';const r=await create();assert.equal((await invoke(checkout,'POST',{reportId:r.reportId})).status,503);const url=process.env.TURSO_DATABASE_URL;delete process.env.TURSO_DATABASE_URL;try{mockProvider();const out=await invoke(analyze,'POST',payload());assert.equal(out.status,200);assert.equal(out.body.storageAvailable,false);assert.equal(out.body.premium,undefined);assert.equal((await invoke(coach,'POST',{})).status,503);}finally{process.env.TURSO_DATABASE_URL=url;}const key=process.env.GEMINI_API_KEY;delete process.env.GEMINI_API_KEY;assert.equal((await invoke(analyze,'POST',payload())).status,503);process.env.GEMINI_API_KEY=key;});
test('invalid and partial Gemini responses are safe; saved base can be resumed',async()=>{await db.execute('DELETE FROM rate_limits');global.fetch=async()=>({ok:true,json:async()=>({candidates:[{finishReason:'MAX_TOKENS'}]})});assert.equal((await invoke(analyze,'POST',payload())).status,503);let count=0;global.fetch=async(u,o)=>{if(++count>1)return {ok:false,status:503};return {ok:true,json:async()=>({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(fixture(JSON.parse(o.body).generationConfig.responseSchema))}]}}]})};};const p=payload(),out=await invoke(analyze,'POST',{...p,stream:true});assert.deepEqual(out.events.map(x=>x.event),['accepted','base','partial']);assert.equal(out.events[1].data.premium,undefined);const id=out.events[0].data.reportId;assert.equal((await R.owned(id,owner)).status,'partial');const calls=mockProvider();assert.equal((await invoke(analyze,'POST',p)).status,200);assert.equal(calls.length,2);});
test('database outage returns safe error; origin and malformed payload protection',async()=>{const url=process.env.TURSO_DATABASE_URL;process.env.TURSO_DATABASE_URL='file:/does-not-exist/para/db';const out=await invoke(reportRoute,'GET',undefined,{},{id:randomUUID()});assert.equal(out.status,503);assert.ok(!out.raw.includes('SQL'));process.env.TURSO_DATABASE_URL=url;assert.equal((await invoke(analyze,'POST',payload(),{origin:'https://attacker.test'})).status,403);const p=payload();p.answers[0].personA=900;assert.equal((await invoke(analyze,'POST',p)).status,400);});
test('delete clears server report and access; cleanup removes expired sensitive records',async()=>{const r=await create();assert.equal((await invoke(reportRoute,'DELETE',undefined,{},{id:r.reportId})).status,200);assert.equal((await invoke(reportRoute,'GET',undefined,{},{id:r.reportId})).status,404);const other=await create();await db.execute('UPDATE reports SET expires_at=0 WHERE id=?',[other.reportId]);await require('../lib/maintenance')();assert.equal(await db.one('SELECT id FROM reports WHERE id=?',[other.reportId]),undefined);});
